steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/volyzen-ai-engine', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/volyzen-ai-engine']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'volyzen-ai-engine',
        '--image', 'gcr.io/$PROJECT_ID/volyzen-ai-engine',
        '--region', 'europe-west4',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/volyzen-ai-engine'

options:
  logging: CLOUD_LOGGING_ONLY
